apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World1111</title>
    </head>
    <body>
        <h1>Hello World</h1>
    </body>
    </html>
